trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: '$(Build.SourcesDirectory)'
  appDir: '$(buildDir)/app'

steps:

# Download google-services.json securely
- task: DownloadSecureFile@1
  name: DownloadGoogleServices
  inputs:
    secureFile: 'google-services.json'

# Copy the file to the correct location
- script: |
    cp $(DownloadGoogleServices.secureFilePath) $(appDir)/google-services.json
  displayName: 'Copy google-services.json to app directory'


# Build the Android App Bundle (AAB)
- task: Gradle@3
  displayName: 'Assemble Android App Bundle (Debug)'
  inputs:
    workingDirectory: '$(buildDir)'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx4096m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean :app:bundleDebug'

# Publish the AAB as a pipeline artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish AAB as Artifact'
  inputs:
    targetPath: '$(outputAab)'
    artifact: 'android-business-card-aab'
    publishLocation: 'pipeline'
