trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  buildDir: '$(Build.SourcesDirectory)'
  appDir: '$(buildDir)/app'

steps:

# Download google-services.json securely
- task: DownloadSecureFile@1
  name: DownloadGoogleServices
  inputs:
    secureFile: 'google-services.json'

# Copy the file to the correct location
- script: |
    cp $(DownloadGoogleServices.secureFilePath) $(appDir)/google-services.json
  displayName: 'Copy google-services.json to app directory'

# Build the Android App Bundle (AAB)
- task: Gradle@2
  displayName: 'Assemble Android App Bundle (Debug)'
  inputs:
    workingDirectory: '$(buildDir)'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx4096m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean :app:bundleDebug'