name: Appdome build-2secure
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  appdome:
    runs-on: ubuntu-latest
    steps:
      - name: Appdome build-2secure
        uses: Appdome/github_build-2secure@latest
        with:
          APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
          TEAM_ID: ${{secrets.TEAM_ID}} # Your team id in appdome
          APP_FILE: ${{github.workspace}}/app/release/app-release.apk # none_protected_application can be pass as path/on/repository OR https://download_link
          FUSION_SET_ID: ${{secrets.FUSION_SET_ID}} #"Appdome Fusion Set_Id Android/iOS"
          SIGN_OPTIONS: "SIGN_ON_APPDOME"
          BUILD_WITH_LOGS: true # Optional
          KEYSTORE_FILE: ${{secrets.KEYSTORE_BASE64}}
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
          KEYSTORE_ALIAS: ${{secrets.KEYSTORE_ALIAS}}
          KEYSTORE_KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
